# Max TX power (keyboard is always near the computer)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Deep sleep after 4 hours (generous — 750mAh battery)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=14400000

# Display config
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=1920
